### PR TITLE
chunk_size and cores default to ppj

### LINKED ISSUE #79: Default chunk_size and cores to ppj
Back in issue #49 we discussed having chunk size defaulting to the ppj, but we lost track of that issue so I'm filing this. 

I'm thinking it the logic should be: unless overridden in the environment or command-line, `-c` and `-j` both default to `--ppj`. That way, you default to running as many commands in parallel in a job as you have processors allocated, and the user only needs to change one option, `--ppj`, if they want to scale that up or down.

### PR DESCRIPTION
**Pull request by pipitone**
This fixes #79

### CODE REVIEW

**Comment by gdevenyi** [comment]
This looks okay to me, one thought, could we generalize this to a "default" class so that i can use it for PR #80 marking as well? Or is that beyond the ability of the class definition?

**Comment by pipitone** [comment]
There might be a way... but it will probably be uncomfortably meta  ;-)

**Comment by gdevenyi** [comment]
Any further thoughts on the meta? Worth it? Otherwise PR #80 will need either it's own default wrapper or an argparse wrapper.

Can you grok the examples here? https://bugs.python.org/issue16399 I can't get them to work.

**Comment by gdevenyi** [comment]
I'm thinking for this we switch to #85 for our defaults implementation, otherwise, we need a ton of metamagics for this, and for #80

**Pull request closed without merging**
