### PR TITLE
Minimum Effort Python API

### PR DESCRIPTION
**Pull request by gkiar**
### New Functionality
- Reorganizes package files to be more Pythonic
- Breaks main functionality into `qbatchParser` and `qbatchDriver` functions
- `qbatchParser` accepts an `args` value, which will be empty when called from the command-line, but parsed when used from within Python. Passing args should be as a list (i.e. emulate how the args would look in `sys.argv`)
- Passing args to `qbatchDriver` is done by `**kwargs`, meaning it can accept arbitrary key value pairs and parse them or ignore them all happily :)

```
from qbatch import qbatchParser as qp
qp(['--help'])
qp(['-n', '-'])

# OR...

from qbatch import qbatchDriver as qd
qd(command_file='file', n=True, logfile='{workdir}/logs')
```

### Known issues
- `qbatchDriver` doesn't impose the defaults set in the argument parser in `qbatchParser`, so that makes it crash unless all defaulted variables are passed. This can be fixed by going through the argument parser and adding links for all variables assigned a "default" value, or by migrating defaults to the function heading so as to not duplicate them

### CODE REVIEW

**Comment by gdevenyi** [comment]
Still remaining is to provide a pythonic interface to submit the task list. Currently still needs a job file. 

Easy to do.

**Comment by gdevenyi** [comment]
Currently _setupVars() is called at the front of both qbatchDriver and qbatchParser, but qbatchParser calls qbatchDriver so in that case its called twice.

I think the solution to this is probably if it were a class init function, if this were done with classes...

Need to think about this a bit more..

**Comment by gkiar** [comment]
@gdevenyi I actually believe this can just be called at the beginning of `qbatchDriver`, I just had it in both places for debugging - I don't think that degree of a refactor is necessary, though if you happened to be running from scratch, I do agree a class structure would be better for this whole thing :)

**Comment by gdevenyi** [comment]
Moved to PR #161

**Pull request closed without merging**
