### PR TITLE
Initial environment variable for batch options, simply appends to existing list

### PR DESCRIPTION
**Pull request by gdevenyi**
This really should override the existing list, but this is currently unsupported in argparse

Only documentation I could find provides example code that doesn't work (anymore?)

### CODE REVIEW

**Comment by pipitone** [comment]
Could you write a custom action to deal with this?

**Comment by pipitone** [comment]
i.e. action checks that if appending to the default list, just replace it, otherwise append

**Comment by gdevenyi** [comment]
That's the idea, but my python-fu isn't strong enough to do it.

**Comment by pipitone** [comment]
Check out PR #83. I create an int subclass to mark default values. You could do the same with lists. It's not perfect, but it works.

**Comment by gdevenyi** [comment]
Hrm. I was thinking of replacing the argparse handler as per various discussions around. This probably much more doable.

**Comment by gdevenyi** [comment]
Should be handled via #85

**Pull request closed without merging**
