### PR TITLE
Implement detection of array and regular dependencies for Torque/PBS

### PR DESCRIPTION
**Pull request by gdevenyi**
Testing on scinet in progress

### CODE REVIEW

**Comment by gdevenyi** [comment]
I... don't understand why this broke tests. I didn't touch the tests...

**Comment by gdevenyi** [comment]
Figured it out, forgot to fix the default return of pbs_find_jobs

**Comment by gdevenyi** [comment]
Need to test if this actually works now. It is very much not clear from the documentation how to specify both afterok and afterarrayok on the same job (this is arguably a rare occurrence, but still)

**Comment by gdevenyi** [comment]
Multiple "-W depend=" results in overriding of the previous ones
Using ":" to specify a different type results in ``[qsub: illegal -W value]``
Using "," to specify a different type results in ``qsub: submit error (Illegal attribute or resource value for  depend)``

Right now, at a loss, checking PBS userlist, as for some reason I can't send mail to it...

**Comment by gdevenyi** [comment]
:( http://www.supercluster.org/pipermail/torqueusers/2016-April/018638.html

Not sure how we can handle this right now, seems as though it's not possible.

**Comment by gdevenyi** [comment]
Fixed in git version of torque: https://github.com/adaptivecomputing/torque/issues/358#issuecomment-221337338

**Comment by gdevenyi** [comment]
@pipitone I now have this working as intended, jobtypes are checked and dependencies are specified correctly.

The only problem is older versions of torque don't allow both afterok and afterarrayok:
```
qsub: submit error (Illegal attribute or resource value for  depend)
qsub call returned error code 168
```

Should I print a warning if there are both array and non-array dependencies so that users are aware?

**Comment by pipitone** [comment]
Yeah. Error out with a helpful message. 

I suppose if we wanted to get clever (and I don't know that we do), we
could in these cases submit two nop jobs that depend on the array and
non-array jobs respectively, and then make the qbatch jobs being
submitted depend on *those* two jobs. But that seems like a lot of work
for a corner case.

**Comment by gdevenyi** [comment]
Yes, cleverness is an option I'm not really wanting to do, I think it's a corner case.

I presume the error code is "something is wrong with depend string", do you think it's safe to assume that it's due to this? We'll have to special-case the error return codes.

I was thinking instead, that we should print a warning if qbatch finds both array and non-array jobs to depend on, explaining the issue.

Does that make sense?

**Comment by gdevenyi** [comment]
hybrid dependencies available in 6.0.2, I suggest we put a warning if we detect them and mention the version where they start working.

**Comment by pipitone** [comment]
Yeah that makes sense.

**Comment by gdevenyi** [comment]
Warning added in the case of finding array and regular job dependencies.

**Pull request merged**
