### PR TITLE
Update documentation and help, more examples!

### PR DESCRIPTION
**Pull request by gdevenyi**
Documentation will set you free.

### CODE REVIEW

**Comment by gdevenyi** [comment]
This currently documents assuming you merge the local command bits.

Needs modification for generalized header options if merged.

**Comment by pipitone** [comment]
Thanks Gabe! Want me to merge conflicts or is this still cooking?

**Comment by gdevenyi** [comment]
I can rebase now that things are merged. I need to add documentation for the generalized header bits anyways.

**Comment by gdevenyi** [comment]
Fixed up and ready for merge.

**Pull request merged**
