### PR TITLE
Add support for 64GB scinet nodes

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Question: should --highmem become --highmem32?

**Comment by pipitone** [comment]
Maybe we should generalize this, huh? We could add a `--node-specs` attribute which you could use to do `--node-specs m64g`

**Comment by gdevenyi** [comment]
--pbs-node-specs ?

**Comment by gdevenyi** [comment]
Superseded by #126

**Pull request closed without merging**
