### PR TITLE
Add preflight check for required programs

### LINKED ISSUE #47: Preflight check for parallel and other dependencies
It would be nice if qbatch [checked](http://stackoverflow.com/questions/377017/test-if-executable-exists-in-python) that `parallel` was in the path before submitting a job so that you don't waste time submitting a job that is going to fail almost surely.

Same goes for `qsub` and `qstat` although missing these would lead to an immediate failure so not nearly as important.

### PR DESCRIPTION
**Pull request by gdevenyi**
Fixes #47

### CODE REVIEW

**Comment by gdevenyi** [comment]
Oh of course, this breaks the travis tests because travis doesn't have qsub yet.

Not sure why this breaks pep8, it passed when I tested it here.

**Comment by pipitone** [comment]
Argggh... travis!

**Comment by pipitone** [comment]
I wonder what we should do... It wouldn't be hard to just configure travis to apt-get install `gridengine-client` even if we don't configure it for now...

**Comment by gdevenyi** [comment]
Will add to Travis config tomorrow and see what it does.

**Pull request merged**
