### PR TITLE
Count jobs, if zero, exit with warning to stderr

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by gdevenyi** [comment]
If jobfile or stdin don't have any lines, don't create a broken qsub job.

The reason I exit with success is so that I can pipe a command to stdin which *may* produce no output and not error out.

**Comment by gdevenyi** [comment]
This will conflict with the local run code since they touch the same lines.

**Comment by pipitone** [comment]
> The reason I exit with success is so that I can pipe a command to stdin which may produce no output and not error out.

Makes sense to me. "Garbage in, garbage out" is not an error. :-)

**Comment by gdevenyi** [comment]
Oi, is that a shot? ;)

Goal for this is to avoid having to create the input jobfiles on scinet, because all that extra IO slows things down pretty substantially.

**Pull request merged**
