### PR TITLE
Enable verbose parallel

### LINKED ISSUE #42: parallel should be more verbose?
Parallel offers the "-v" option, which prints the job run before each output. This helps in various debugging when a command in a job list fails:
```
       -v       Verbose.  Print the job to be run on stdout (standard output).
```

Should this depend on a verbose flag? Or be the deafult.

### PR DESCRIPTION
**Pull request by gdevenyi**
Fixes #42

### CODE REVIEW

**Comment by gdevenyi** [comment]
Oh, I see I have to rewrite the tests for this. Yay :)

**Comment by gdevenyi** [comment]
Hrm, I can't fix the tests because I don't know how the existing outputs are being constructed.

They use some map thing I've never seen before.

**Comment by gdevenyi** [comment]
Hrm, the way travis is calling the code is different than how it does locally.

Different version of gnu parallel?

**Comment by gdevenyi** [comment]
Yes, different version of gnu parallel

https://www.gnu.org/software/parallel/parallel_tutorial.html#Profiles

**Comment by gdevenyi** [comment]
Had to update travis to ubuntu trusty version to get a modern version of gnu parallel

**Comment by gdevenyi** [comment]
Fixes #42

**Comment by pipitone** [comment]
Thanks!

**Pull request merged**
