### PR TITLE
Generalize free-form options to allow for headers in job files

### PR DESCRIPTION
**Pull request by gdevenyi**
Allows things like sourcing of environment scripts (think magetbrain activate) or module loading.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Eventual goal of this is to do away with the environment inherit command. Turns out we've been taxing scinet with it, might be causing some hard-to-trace errors.

If this works as expected, I think the bash -l should be done away with.

**Comment by pipitone** [comment]
Thanks Gabe. Ideally I'd like to support environment inheriting also, since it's incredibly convenient ultimately. Don't you think?

**Comment by gdevenyi** [comment]
Yup, it should be supported, somehow, we should probably make "-V" optional somehow, to allow for either method.

Alternatively, we could do our own environment support, perhaps dump the user's environment to a script and then source it on job run?

**Comment by pipitone** [comment]
Moving this discussion over to #25

**Pull request merged**
